/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.smoke;

import com.epam.jdi.InitTests;
import com.epam.jdi.api.LaunchControllerApi;
import com.epam.jdi.model.StartLaunchRQ;
import com.epam.jdi.model.StartLaunchRS;
import org.assertj.core.api.Assertions;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static com.epam.http.requests.ServiceInit.init;
import static com.epam.jdi.api.LaunchControllerApi.startLaunch;

/**
 * API tests for UserControllerApi
 */
public class demo extends InitTests {

    StartLaunchRS startLaunchRS;

    @BeforeClass
    public void initServices() {
        init(LaunchControllerApi.class, spec);
    }

    @Test
    public void startLaunchTest() {
        StartLaunchRQ startLaunchRQ = new StartLaunchRQ().setName("Launch_Test").setStartTime(now());
        String json = gson.toJson(startLaunchRQ);
        startLaunchRS = startLaunch.pathParams(testProject).body(json).callAsData();
        Assertions.assertThat(startLaunchRS.getId()).describedAs("Launch id is empty").isNotEmpty();
        Assertions.assertThat(startLaunchRS.getNumber()).describedAs("Launch number is empty").isGreaterThan(0);
    }


}
