/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.model;

import com.epam.jdi.tools.DataClass;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AnalyzeLaunchRQ
 */

@JsonIgnoreProperties(ignoreUnknown = true)
public class AnalyzeLaunchRQ extends DataClass<AnalyzeLaunchRQ> {

    public AnalyzerModeEnum analyzerMode;

    /**
     * Gets or Sets analyzerMode
     */
    public enum AnalyzerModeEnum {
        ALL("ALL"),

        LAUNCH_NAME("LAUNCH_NAME"),

        CURRENT_LAUNCH("CURRENT_LAUNCH");

        private String value;

        AnalyzerModeEnum(String value) {
            this.value = value;
        }
    }

    public AnalyzerTypeNameEnum analyzerTypeName;

    /**
     * Gets or Sets analyzerTypeName
     */
    public enum AnalyzerTypeNameEnum {
        AUTOANALYZER("autoAnalyzer"),

        PATTERNANALYZER("patternAnalyzer");

        private String value;

        AnalyzerTypeNameEnum(String value) {
            this.value = value;
        }
    }

    public Long launchId;
}

