/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.model;

import com.epam.jdi.tools.DataClass;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * CreateUserRQFull
 */

@Data
@Accessors(chain = true)
@JsonIgnoreProperties(ignoreUnknown = true)
public class CreateUserRQFull extends DataClass<CreateUserRQFull> {

    public AccountRoleEnum accountRole;

    /**
     * Gets or Sets accountRole
     */
    public enum AccountRoleEnum {
        USER("USER"),

        ADMINISTRATOR("ADMINISTRATOR");

        private String value;

        AccountRoleEnum(String value) {
            this.value = value;
        }
    }

    public String defaultProject;
    public String email;
    public String fullName;
    public String login;
    public String password;
    public ProjectRoleEnum projectRole;

    /**
     * Gets or Sets projectRole
     */
    public enum ProjectRoleEnum {
        CUSTOMER("CUSTOMER"),

        MEMBER("MEMBER"),

        LEAD("LEAD"),

        PROJECT_MANAGER("PROJECT_MANAGER");

        private String value;

        ProjectRoleEnum(String value) {
            this.value = value;
        }
    }

}

