/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.model;

import com.epam.jdi.tools.DataClass;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import lombok.experimental.Accessors;

import java.util.Date;

/**
 * LogResource
 */

@Data
@Accessors(chain = true)
@JsonIgnoreProperties(ignoreUnknown = true)
public class LogResource extends DataClass<LogResource> {

    public BinaryContent binaryContent;
    public Long id;
    public Long itemId;
    public Long launchId;
    public LevelEnum level;

    /**
     * Gets or Sets level
     */
    public enum LevelEnum {
        ERROR("error"),

        WARN("warn"),

        INFO("info"),

        DEBUG("debug"),

        TRACE("trace"),

        FATAL("fatal"),

        UNKNOWN("unknown");

        private String value;

        LevelEnum(String value) {
            this.value = value;
        }
    }

    public String message;
    public String thumbnail;
    public Date time;
    public String uuid;
}

