/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.model;

import com.epam.jdi.tools.DataClass;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * SearchLogRs
 */

@JsonIgnoreProperties(ignoreUnknown = true)
public class SearchLogRs extends DataClass<SearchLogRs> {

    public Double duration;
    public Issue issue;
    public Long itemId;
    public String itemName;
    public Long launchId;
    public String launchName;
    public String path;
    public String status;
}

