/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.model;

import com.epam.jdi.tools.DataClass;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;

/**
 * TestItemResource
 */

@JsonIgnoreProperties(ignoreUnknown = true)
public class TestItemResource extends DataClass<TestItemResource> {

    public String codeRef;
    public String description;
    public Date endTime;
    public Boolean hasChildren;
    public Boolean hasStats;
    public Long id;
    public Issue issue;
    public Long launchId;
    public String launchStatus;
    public String name;
    public Long parent;
    public String path;
    public PathNameResource pathNames;
    public Date startTime;
    public StatisticsResource statistics;
    public String status;
    public Integer testCaseHash;
    public String testCaseId;
    public String type;
    public String uniqueId;
    public String uuid;
}

