/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.model;

import com.epam.jdi.tools.DataClass;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * UserResource
 */

@JsonIgnoreProperties(ignoreUnknown = true)
public class UserResource extends DataClass<UserResource> {

    public String accountType;
    public String email;
    public String fullName;
    public Long id;
    public Object metadata;
    public String photoId;
    public Boolean photoLoaded;
    public String userId;
    public String userRole;
}

