language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get -y install jq
  - java -Xmx32m -version
before_script:
  - ls -lah
addons:
  apt:
    packages:
      - openjdk-8-jdk

env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
    - PATH="$JAVA_HOME/bin:$PATH"
    - HTTP_TESTS="com.epam.jdi.dark:jdi-dark-demo-rp"
    - SUT_LOGIN="test-user"
    - SUT_PASSWORD="Fqvq1s0S"
    - WITH_TESTS_PARAMS="-Dsut_username=$SUT_LOGIN -Dsut_password=$SUT_PASSWORD"


stages:
  - prepare
  - compile
  - test

jobs:
  include:
    - stage: prepare
      name: Welcome to jdi dark demo
      script:
        - echo ------------------- WELCOME TO JDI DARK DEMO ----------------------
        - mvn --version

    - stage: compile
      name: Compile jdi dark demo code
      script:
        - mvn install -DskipTests

    - stage: test
      name: Run tests
      script:
        - mvn -ntp install -DskipTests
        - mvn verify -pl $HTTP_TESTS $WITH_TESTS_PARAMS

after_failure:
  - echo "Build was failed"
after_success:
  - echo "Build was successful"
after_script:
  - du -d 1 -h ./
  - ls -la
# extra time during long builds
install:
  - travis_wait