/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.tests.steps;

import com.epam.jdi.api.UserControllerApi;
import com.epam.jdi.model.ChangePasswordRQ;
import io.cucumber.java.en.When;

import static com.epam.jdi.http.Utils.restResponse;

/**
 * Steps for UserControllerApi
 */
public class UserControllerSteps extends Global {

    @When("change password from {string} to {string}")
    public void changePasswordUsingPOSTTest(String oldPassword, String newPassword) {
        restResponse.set(UserControllerApi.changePasswordUsingPOST
                .post(new ChangePasswordRQ().setOldPassword(oldPassword)
                        .setNewPassword(newPassword)));
    }

}
