/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.auth;

import com.epam.http.annotations.POST;
import com.epam.http.annotations.ServiceDomain;
import com.epam.http.requests.RestMethod;

@ServiceDomain("${uat}")
public class AuthTokenApi {

    /**
     * Get user token
     *
     * @param grant_type /form/ String (required)
     * @param username /form/ String (required)
     * @param password /form/ String (required)
     * @return String
     */
    @POST("/sso/oauth/token")
    public static RestMethod getUserToken;

}
