/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.model;

import com.epam.jdi.model.StatisticsResource;
import com.epam.jdi.tools.DataClass;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import lombok.experimental.Accessors;

import java.util.Date;

/**
 * LaunchResource
 */

@Data
@Accessors(chain = true)
@JsonIgnoreProperties(ignoreUnknown = true)
public class LaunchResource extends DataClass<LaunchResource> {

    public Double approximateDuration;
    public String description;
    public Date endTime;
    public Boolean hasRetries;
    public Long id;
    public Date lastModified;
    public ModeEnum mode;

    /**
     * Gets or Sets mode
     */
    public enum ModeEnum {
        DEFAULT("DEFAULT"),

        DEBUG("DEBUG");

        private String value;

        ModeEnum(String value) {
            this.value = value;
        }
    }

    public String name;
    public Long number;
    public String owner;
    public Boolean rerun;
    public Boolean share;
    public Date startTime;
    public StatisticsResource statistics;
    public String status;
    public String uuid;
}

