/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.api;

import com.epam.http.response.RestResponse;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static com.epam.http.requests.ServiceInit.init;

/**
 * API tests for ActivityControllerApi
 */
public class ActivityControllerApiTest {

    @BeforeClass
    public void before() {
        init(ActivityControllerApi.class);
    }


    /**
     * Get activities for project
     */
    @Test
    public void getActivitiesUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = ActivityControllerApi.getActivitiesUsingGET.callPathParams("Test Project");
        resp.isOk();
    }

    /**
     * Get activities for project
     */
    @Test
    public void getActivitiesUsingGET1Test() {
        // TODO: add call parameters and test validations
        RestResponse resp = ActivityControllerApi.getActivitiesUsingGET1.call();
        resp.isOk();
    }

    /**
     * getActivity
     */
    @Test
    public void getActivityUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = ActivityControllerApi.getActivityUsingGET.call();
        resp.isOk();
    }

    /**
     * Get activities for test item
     */
    @Test
    public void getTestItemActivitiesUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = ActivityControllerApi.getTestItemActivitiesUsingGET.call();
        resp.isOk();
    }

}
