/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.epam.jdi.api;

import com.epam.http.response.RestResponse;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static com.epam.http.requests.ServiceInit.init;

/**
 * API tests for LaunchAsyncControllerApi
 */
public class LaunchAsyncControllerApiTest {

    private LaunchAsyncControllerApi service;

    @BeforeClass
    public void before() { service = init(LaunchAsyncControllerApi.class); }

    
    /**
     * Finish launch for specified project
     * 
     */
    @Test
    public void finishLaunchUsingPUTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = LaunchAsyncControllerApi.finishLaunchUsingPUTJSON.call();
        resp.isOk();
    }
    
    /**
     * Merge set of specified launches in common one
     * 
     */
    @Test
    public void mergeLaunchesUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = LaunchAsyncControllerApi.mergeLaunchesUsingPOSTJSON.call();
        resp.isOk();
    }
    
    /**
     * Starts launch for specified project
     * 
     */
    @Test
    public void startLaunchUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = LaunchAsyncControllerApi.startLaunchUsingPOSTJSON.call();
        resp.isOk();
    }
    
}
