/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.api;

import com.epam.http.response.RestResponse;
import com.epam.jdi.InitTests;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Ignore;
import org.testng.annotations.Test;

import static com.epam.http.requests.ServiceInit.init;

/**
 * API tests for LaunchAsyncControllerApi
 */
public class LaunchAsyncControllerApiTest extends InitTests {

    @BeforeClass
    public void before() {
        init(LaunchAsyncControllerApi.class, spec);
    }


    /**
     * Finish launch for specified project
     */
    @Ignore
    @Test
    public void finishLaunchUsingPUTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = LaunchAsyncControllerApi.finishLaunchUsingPUTJSON.call();
        resp.isOk();
    }

    /**
     * Merge set of specified launches in common one
     */
    @Ignore
    @Test
    public void mergeLaunchesUsingPOSTTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = LaunchAsyncControllerApi.mergeLaunchesUsingPOST.call();
        resp.isOk();
    }

    /**
     * Starts launch for specified project
     */
    @Ignore
    @Test
    public void startLaunchUsingPOSTTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = LaunchAsyncControllerApi.startLaunchUsingPOST.call();
        resp.isOk();
    }

}
