/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.api;

import com.epam.http.response.RestResponse;
import com.epam.jdi.InitTests;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Ignore;
import org.testng.annotations.Test;

import static com.epam.http.requests.ServiceInit.init;

/**
 * API tests for ProjectSettingsControllerApi
 */
public class ProjectSettingsControllerApiTest extends InitTests {

    @BeforeClass
    public void before() {
        init(ProjectSettingsControllerApi.class, spec);
    }


    /**
     * Create pattern template for items&#39; log messages pattern analysis
     */
    @Ignore
    @Test
    public void createPatternTemplateUsingPOSTTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = ProjectSettingsControllerApi.createPatternTemplateUsingPOST.call();
        resp.isOk();
    }

    /**
     * Creation of custom project specific issue sub-type
     */
    @Ignore
    @Test
    public void createProjectIssueSubTypeUsingPOSTTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = ProjectSettingsControllerApi.createProjectIssueSubTypeUsingPOST.call();
        resp.isOk();
    }

    /**
     * Delete pattern template for items&#39; log messages pattern analysis
     */
    @Ignore
    @Test
    public void deletePatternTemplateUsingDELETETest() {
        // TODO: add call parameters and test validations
        RestResponse resp = ProjectSettingsControllerApi.deletePatternTemplateUsingDELETE.call();
        resp.isOk();
    }

    /**
     * Delete custom project specific issue sub-type
     */
    @Ignore
    @Test
    public void deleteProjectIssueSubTypeUsingDELETETest() {
        // TODO: add call parameters and test validations
        RestResponse resp = ProjectSettingsControllerApi.deleteProjectIssueSubTypeUsingDELETE.call();
        resp.isOk();
    }

    /**
     * Get project specific issue sub-types
     * Only for users that are assigned to the project
     */
    @Ignore
    @Test
    public void getProjectSettingsUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = ProjectSettingsControllerApi.getProjectSettingsUsingGET.call();
        resp.isOk();
    }

    /**
     * Update pattern template for items&#39; log messages pattern analysis
     */
    @Ignore
    @Test
    public void updatePatternTemplateUsingPUTTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = ProjectSettingsControllerApi.updatePatternTemplateUsingPUT.call();
        resp.isOk();
    }

    /**
     * Update of custom project specific issue sub-type
     */
    @Ignore
    @Test
    public void updateProjectIssueSubTypeUsingPUTTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = ProjectSettingsControllerApi.updateProjectIssueSubTypeUsingPUT.call();
        resp.isOk();
    }

}
