/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.epam.jdi.api;

import com.epam.http.response.RestResponse;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static com.epam.http.requests.ServiceInit.init;

/**
 * API tests for SettingsControllerApi
 */
public class SettingsControllerApiTest {

    private SettingsControllerApi service;

    @BeforeClass
    public void before() { service = init(SettingsControllerApi.class); }

    
    /**
     * Get server settings
     * 
     */
    @Test
    public void getServerSettingsUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = SettingsControllerApi.getServerSettingsUsingGET.call();
        resp.isOk();
    }
    
    /**
     * Update analytics settings
     * 
     */
    @Test
    public void saveAnalyticsSettingsUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = SettingsControllerApi.saveAnalyticsSettingsUsingPOSTJSON.call();
        resp.isOk();
    }
    
    /**
     * Update analytics settings
     * 
     */
    @Test
    public void saveAnalyticsSettingsUsingPUTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = SettingsControllerApi.saveAnalyticsSettingsUsingPUTJSON.call();
        resp.isOk();
    }
    
}
