/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.api;

import com.epam.http.response.RestResponse;
import com.epam.jdi.auth.AuthTokenApi;
import com.epam.jdi.model.ChangePasswordRQ;
import com.epam.jdi.model.CreateUserRQ;
import io.restassured.authentication.BasicAuthScheme;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Ignore;
import org.testng.annotations.Test;

import static com.epam.http.requests.RequestDataFactory.auth;
import static com.epam.http.requests.ServiceInit.init;
import static com.epam.jdi.api.UserControllerApi.changePasswordUsingPOSTJSON;
import static com.epam.jdi.api.UserControllerApi.createUserBidUsingPOSTJSON;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

/**
 * API tests for UserControllerApi
 */
public class UserControllerApiTest {

    @BeforeClass
    public void before() {
        init(AuthTokenApi.class);
        BasicAuthScheme basicAuthScheme = new BasicAuthScheme();
        basicAuthScheme.setUserName("ui");
        basicAuthScheme.setPassword("uiman");
        String token = AuthTokenApi.getUserToken.call(
                auth(basicAuthScheme)
                        .addFormParams().addAll(new Object[][]{
                        {"grant_type", "password"},
                        {"username", "test-user"},
                        {"password", "Fqvq1s0S"}}))
                .getRaResponse().jsonPath().getString("access_token");
        init(UserControllerApi.class, given().auth().preemptive().oauth2(token));
    }


    /**
     * Change own password
     */
    @Test
    public void changePasswordUsingPOSTJSONTest() {
        changePasswordUsingPOSTJSON
                .post(new ChangePasswordRQ().setOldPassword("wrong")
                        .setNewPassword("new"))
                .assertThat()
                .statusCode(400)
                .body("errorCode", equalTo(4001))
                .body("message",
                        equalTo("Incorrect Request. [Field 'newPassword' should have size from '4' to '256'.] "));

        changePasswordUsingPOSTJSON
                .post(new ChangePasswordRQ().setOldPassword("wrong")
                        .setNewPassword("newPassword"))
                .assertThat()
                .statusCode(400)
                .body("errorCode", equalTo(40010))
                .body("message",
                        equalTo("Forbidden operation. Old password not match with stored."));
    }

    /**
     * Register invitation for user who will be created
     */
    @Test
    public void createUserBidUsingPOSTJSONTest() {
        createUserBidUsingPOSTJSON.post(new CreateUserRQ()
                .setDefaultProject("wrongProject")
                .setEmail("test@test.com"))
                .assertThat()
                .statusCode(400)
                .body("errorCode", equalTo(4001))
                .body("message",
                        equalTo("Incorrect Request. [Field 'role' should not contain only white spaces and shouldn't be empty.] "));
    }

    /**
     * Create specified user
     * Allowable only for users with administrator role
     */
    @Ignore
    @Test
    public void createUserByAdminUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.createUserByAdminUsingPOSTJSON.call();
        resp.isOk();
    }

    /**
     * Activate invitation and create user in system
     */
    @Ignore
    @Test
    public void createUserUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.createUserUsingPOSTJSON.call();
        resp.isOk();
    }

    /**
     * Delete specified user
     * Allowable only for users with administrator role
     */
    @Ignore
    @Test
    public void deleteUserUsingDELETETest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.deleteUserUsingDELETE.call();
        resp.isOk();
    }

    /**
     * Delete specified users by ids
     */
    @Ignore
    @Test
    public void deleteUsersUsingDELETETest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.deleteUsersUsingDELETE.call();
        resp.isOk();
    }

    /**
     * Edit specified user
     * Only for administrators and profile&#39;s owner
     */
    @Ignore
    @Test
    public void editUserUsingPUTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.editUserUsingPUTJSON.call();
        resp.isOk();
    }

    /**
     * Exports information about all users
     * Allowable only for users with administrator role
     */
    @Ignore
    @Test
    public void exportUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.exportUsingGET.call();
        resp.isOk();
    }

    /**
     * findUsers
     */
    @Ignore
    @Test
    public void findUsersUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.findUsersUsingGET.call();
        resp.isOk();
    }

    /**
     * Return information about current logged-in user
     */
    @Ignore
    @Test
    public void getMyselfUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getMyselfUsingGET.call();
        resp.isOk();
    }

    /**
     * Return information about current logged-in user
     */
    @Ignore
    @Test
    public void getMyselfUsingGET1Test() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getMyselfUsingGET1.call();
        resp.isOk();
    }

    /**
     * getUserBidInfo
     */
    @Ignore
    @Test
    public void getUserBidInfoUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getUserBidInfoUsingGET.call();
        resp.isOk();
    }

    /**
     * getUserProjects
     */
    @Ignore
    @Test
    public void getUserProjectsUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getUserProjectsUsingGET.callPathParams("test-user");
        resp.isOk();
    }

    /**
     * Return information about specified user
     * Only for administrators and profile&#39;s owner
     */
    @Ignore
    @Test
    public void getUserUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getUserUsingGET.call();
        resp.isOk();
    }

    /**
     * Return information about all users
     * Allowable only for users with administrator role
     */
    @Ignore
    @Test
    public void getUsersUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getUsersUsingGET.call();
        resp.isOk();
    }

    /**
     * Check if a restore password bid exists
     */
    @Ignore
    @Test
    public void isRestorePasswordBidExistUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.isRestorePasswordBidExistUsingGET.call();
        resp.isOk();
    }

    /**
     * Reset password
     */
    @Ignore
    @Test
    public void resetPasswordUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.resetPasswordUsingPOSTJSON.call();
        resp.isOk();
    }

    /**
     * Create a restore password request
     */
    @Ignore
    @Test
    public void restorePasswordUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.restorePasswordUsingPOSTJSON.call();
        resp.isOk();
    }

    /**
     * validateInfo
     */
    @Ignore
    @Test
    public void validateInfoUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.validateInfoUsingGET.call();
        resp.isOk();
    }

}
