/*
 * Report Portal
 * Report Portal API documentation
 *
 * OpenAPI spec version: 5.2.0
 * Contact: Support EPMC-TST Report Portal <SupportEPMC-TSTReportPortal@epam.com>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.epam.jdi.api;

import com.epam.http.response.RestResponse;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static com.epam.http.requests.ServiceInit.init;

/**
 * API tests for UserControllerApi
 */
public class UserControllerApiTest {

    @BeforeClass
    public void before() {
        init(UserControllerApi.class);
    }


    /**
     * Change own password
     */
    @Test
    public void changePasswordUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.changePasswordUsingPOSTJSON.call();
        resp.isOk();
    }

    /**
     * Register invitation for user who will be created
     */
    @Test
    public void createUserBidUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.createUserBidUsingPOSTJSON.call();
        resp.isOk();
    }

    /**
     * Create specified user
     * Allowable only for users with administrator role
     */
    @Test
    public void createUserByAdminUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.createUserByAdminUsingPOSTJSON.call();
        resp.isOk();
    }

    /**
     * Activate invitation and create user in system
     */
    @Test
    public void createUserUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.createUserUsingPOSTJSON.call();
        resp.isOk();
    }

    /**
     * Delete specified user
     * Allowable only for users with administrator role
     */
    @Test
    public void deleteUserUsingDELETETest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.deleteUserUsingDELETE.call();
        resp.isOk();
    }

    /**
     * Delete specified users by ids
     */
    @Test
    public void deleteUsersUsingDELETETest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.deleteUsersUsingDELETE.call();
        resp.isOk();
    }

    /**
     * Edit specified user
     * Only for administrators and profile&#39;s owner
     */
    @Test
    public void editUserUsingPUTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.editUserUsingPUTJSON.call();
        resp.isOk();
    }

    /**
     * Exports information about all users
     * Allowable only for users with administrator role
     */
    @Test
    public void exportUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.exportUsingGET.call();
        resp.isOk();
    }

    /**
     * findUsers
     */
    @Test
    public void findUsersUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.findUsersUsingGET.call();
        resp.isOk();
    }

    /**
     * Return information about current logged-in user
     */
    @Test
    public void getMyselfUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getMyselfUsingGET.call();
        resp.isOk();
    }

    /**
     * Return information about current logged-in user
     */
    @Test
    public void getMyselfUsingGET1Test() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getMyselfUsingGET1.call();
        resp.isOk();
    }

    /**
     * getUserBidInfo
     */
    @Test
    public void getUserBidInfoUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getUserBidInfoUsingGET.call();
        resp.isOk();
    }

    /**
     * getUserProjects
     */
    @Test
    public void getUserProjectsUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getUserProjectsUsingGET.call();
        resp.isOk();
    }

    /**
     * Return information about specified user
     * Only for administrators and profile&#39;s owner
     */
    @Test
    public void getUserUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getUserUsingGET.call();
        resp.isOk();
    }

    /**
     * Return information about all users
     * Allowable only for users with administrator role
     */
    @Test
    public void getUsersUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.getUsersUsingGET.call();
        resp.isOk();
    }

    /**
     * Check if a restore password bid exists
     */
    @Test
    public void isRestorePasswordBidExistUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.isRestorePasswordBidExistUsingGET.call();
        resp.isOk();
    }

    /**
     * Reset password
     */
    @Test
    public void resetPasswordUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.resetPasswordUsingPOSTJSON.call();
        resp.isOk();
    }

    /**
     * Create a restore password request
     */
    @Test
    public void restorePasswordUsingPOSTJSONTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.restorePasswordUsingPOSTJSON.call();
        resp.isOk();
    }

    /**
     * validateInfo
     */
    @Test
    public void validateInfoUsingGETTest() {
        // TODO: add call parameters and test validations
        RestResponse resp = UserControllerApi.validateInfoUsingGET.call();
        resp.isOk();
    }

}
